# Generated by Django 5.2 on 2025-04-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="student",
            name="section",
        ),
        migrations.AddField(
            model_name="student",
            name="vaccination_status",
            field=models.BooleanField(default=False),
        ),
    ]
