# Generated by Django 5.2 on 2025-04-27 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_gender_remove_student_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccinationDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("target_grades", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="vaccinated_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vaccinated_students",
                to="students.vaccinationdrive",
            ),
        ),
    ]
