# Generated by Django 5.2 on 2025-05-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_vaccinationdrive_student_vaccinated_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="vaccinated_in",
        ),
        migrations.DeleteModel(
            name="VaccinationDrive",
        ),
    ]
