# Generated by Django 5.2 on 2025-04-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drives", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vaccinationdrive",
            old_name="scheduled_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="vaccinationdrive",
            old_name="vaccine_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="vaccinationdrive",
            name="created_at",
        ),
    ]
